[2025-04-23T13:37:45.014+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-23T13:37:45.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T13:37:43.055120+00:00 [queued]>
[2025-04-23T13:37:45.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T13:37:43.055120+00:00 [queued]>
[2025-04-23T13:37:45.030+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-23T13:37:45.038+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_preprocessing> on 2025-04-23 13:37:43.055120+00:00
[2025-04-23T13:37:45.048+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=490) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T13:37:45.049+0000] {standard_task_runner.py:63} INFO - Started process 492 to run task
[2025-04-23T13:37:45.048+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_pipeline', 'run_preprocessing', 'manual__2025-04-23T13:37:43.055120+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocessing.py', '--cfg-path', '/tmp/tmpjk45t81i']
[2025-04-23T13:37:45.050+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask run_preprocessing
[2025-04-23T13:37:45.078+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T13:37:43.055120+00:00 [running]> on host 73223bf8df73
[2025-04-23T13:37:45.120+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocessing_pipeline' AIRFLOW_CTX_TASK_ID='run_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T13:37:43.055120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T13:37:43.055120+00:00'
[2025-04-23T13:37:45.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-23T13:37:45.121+0000] {dag_preprocessing.py:119} INFO - Esecuzione del task di preprocessing iniziata.
[2025-04-23T13:37:45.121+0000] {dag_preprocessing.py:39} INFO - Avvio del preprocessing dei dati...
[2025-04-23T13:37:45.121+0000] {dag_preprocessing.py:23} INFO - Inizializzazione di NLTK...
[2025-04-23T13:37:45.121+0000] {dag_preprocessing.py:28} INFO - Scaricamento 'punkt'...
[2025-04-23T13:37:45.383+0000] {dag_preprocessing.py:28} INFO - Scaricamento 'stopwords'...
[2025-04-23T13:37:45.384+0000] {dag_preprocessing.py:28} INFO - Scaricamento 'wordnet'...
[2025-04-23T13:37:45.447+0000] {dag_preprocessing.py:32} INFO - Risorse NLTK scaricate correttamente.
[2025-04-23T13:37:45.448+0000] {dag_preprocessing.py:43} INFO - Percorso previsto per il CSV: /opt/***/sentiment_data/all-data.csv
[2025-04-23T13:37:45.448+0000] {dag_preprocessing.py:46} INFO - Caricamento del file CSV...
[2025-04-23T13:37:45.473+0000] {dag_preprocessing.py:48} INFO - File CSV caricato correttamente, numero di righe: 4846
[2025-04-23T13:37:45.474+0000] {dag_preprocessing.py:54} INFO - Inizializzazione degli strumenti di preprocessamento...
[2025-04-23T13:37:45.477+0000] {dag_preprocessing.py:58} INFO - Strumenti di preprocessamento inizializzati.
[2025-04-23T13:37:45.478+0000] {dag_preprocessing.py:93} INFO - Inizio preprocessamento del testo...
[2025-04-23T13:37:45.481+0000] {dag_preprocessing.py:67} INFO - Inizio preprocessamento del testo: According to Gran , the compan...
[2025-04-23T13:37:45.481+0000] {dag_preprocessing.py:74} INFO - Verifica se la risorsa 'punkt' Ã¨ disponibile...
[2025-04-23T13:37:45.481+0000] {dag_preprocessing.py:81} INFO - Tokenizzazione del testo...
[2025-04-23T13:37:45.482+0000] {dag_preprocessing.py:84} ERROR - Errore nella tokenizzazione del testo: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T13:37:45.482+0000] {dag_preprocessing.py:97} ERROR - Errore durante il preprocessamento: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T13:37:45.482+0000] {dag_preprocessing.py:124} ERROR - Errore nel task di preprocessing: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T13:37:45.482+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-23T13:37:45.483+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-23T13:37:45.488+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=preprocessing_pipeline, task_id=run_preprocessing, run_id=manual__2025-04-23T13:37:43.055120+00:00, execution_date=20250423T133743, start_date=20250423T133745, end_date=20250423T133745
[2025-04-23T13:37:45.504+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-23T13:37:45.519+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T13:37:45.520+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
