[2025-04-23T12:13:03.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-23T12:13:03.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:13:00.469633+00:00 [queued]>
[2025-04-23T12:13:03.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:13:00.469633+00:00 [queued]>
[2025-04-23T12:13:03.360+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-23T12:13:03.367+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_preprocessing> on 2025-04-23 12:13:00.469633+00:00
[2025-04-23T12:13:03.374+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T12:13:03.375+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_pipeline', 'run_preprocessing', 'manual__2025-04-23T12:13:00.469633+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocessing.py', '--cfg-path', '/tmp/tmppvl9366a']
[2025-04-23T12:13:03.376+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2025-04-23T12:13:03.376+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_preprocessing
[2025-04-23T12:13:03.401+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:13:00.469633+00:00 [running]> on host 558735b76edf
[2025-04-23T12:13:03.438+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocessing_pipeline' AIRFLOW_CTX_TASK_ID='run_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T12:13:00.469633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T12:13:00.469633+00:00'
[2025-04-23T12:13:03.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-23T12:13:03.440+0000] {dag_preprocessing.py:92} INFO - Esecuzione del task di preprocessing iniziata.
[2025-04-23T12:13:03.440+0000] {dag_preprocessing.py:27} INFO - Avvio del preprocessing dei dati...
[2025-04-23T12:13:03.440+0000] {dag_preprocessing.py:31} INFO - Percorso previsto per il CSV: /opt/***/sentiment_data/all-data.csv
[2025-04-23T12:13:03.440+0000] {dag_preprocessing.py:34} INFO - Caricamento del file CSV...
[2025-04-23T12:13:03.442+0000] {dag_preprocessing.py:38} ERROR - File non trovato: /opt/***/sentiment_data/all-data.csv. Verifica che il file sia stato copiato nel container e che il path sia corretto.
[2025-04-23T12:13:03.442+0000] {dag_preprocessing.py:97} ERROR - Errore nel task di preprocessing: [Errno 2] No such file or directory: '/opt/***/sentiment_data/all-data.csv'
[2025-04-23T12:13:03.442+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-23T12:13:03.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-23T12:13:03.446+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=preprocessing_pipeline, task_id=run_preprocessing, run_id=manual__2025-04-23T12:13:00.469633+00:00, execution_date=20250423T121300, start_date=20250423T121303, end_date=20250423T121303
[2025-04-23T12:13:03.474+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-23T12:13:03.483+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T12:13:03.484+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
